# Generated by Django 4.2 on 2023-05-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subtitle')),
            ],
        ),
        migrations.CreateModel(
            name='BoardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=200)),
                ('boardtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.boardtitle')),
            ],
        ),
    ]
