# Generated by Django 4.2 on 2023-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_boardtitle_boardelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chart_images/')),
            ],
        ),
    ]
